<a href="https://colab.research.google.com/github/Phanttan/Deep-learning-with-Python-Francois-Chollet/blob/main/3_7_predicting_house_prices_asUnderstanding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Boston Housing price with regression example

## Loading Data

In [ ]:
from keras.datasets import boston_housing
(train_data, train_targets), (test_data, test_targets) = boston_housing.load_data()

## Preparing data

### Normalizing data (mean = 0, std = 1)

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(train_data)
train_data = scaler.transform(train_data)
train_data.mean(axis=0)

array([-1.01541438e-16,  1.09923072e-17,  1.74337992e-15, -1.26686340e-16,
       -5.25377321e-15,  6.41414864e-15,  2.98441140e-16,  4.94653823e-16,
        1.12671149e-17, -1.98136337e-16,  2.36686358e-14,  5.95679996e-15,
        6.13920356e-16])

In [ ]:
from sklearn.preprocessing import StandardScaler
train_targets = train_targets.reshape(-1,1)
scaler = StandardScaler()
train_targets = scaler.fit_transform(train_targets)
#train_targets = scaler.transform(train_targets)
train_targets.mean(axis=0)

array([3.12181524e-16])

## Build a network

In [ ]:
from keras import models
from keras import layers

def build_model():
    model = models.Sequential()
    model.add(layers.Dense(64, activation='relu', 
                           input_shape=(train_data.shape[1],)))
    model.add(layers.Dense(64, activation='relu'))
    model.add(layers.Dense(1)) # no activation argument for linear layer because of scalar regression
    model.compile(optimizer='rmsprop', loss='mse')#, metric=['mae'])
    return model

## Validation using K-fold validation

In [ ]:
from sklearn.model_selection import cross_val_score
from keras.wrappers.scikit_learn import KerasClassifier
neural_network = KerasClassifier(build_fn=build_model, 
                                 epochs=100,
                                 batch_size=100)

In [ ]:
kfold_score = cross_val_score(neural_network, train_data, train_targets, cv=3, scoring='neg_mean_absolute_error',verbose=0)

Epoch 1/100
3/3 [==============================] - 0s 3ms/step - loss: 8331.6045
Epoch 2/100
3/3 [==============================] - 0s 2ms/step - loss: 8225.3076
Epoch 3/100
3/3 [==============================] - 0s 2ms/step - loss: 8143.2734
Epoch 4/100
3/3 [==============================] - 0s 2ms/step - loss: 8067.7378
Epoch 5/100
3/3 [==============================] - 0s 2ms/step - loss: 7990.1079
Epoch 6/100
3/3 [==============================] - 0s 2ms/step - loss: 7908.8105
Epoch 7/100
3/3 [==============================] - 0s 2ms/step - loss: 7824.4219
Epoch 8/100
3/3 [==============================] - 0s 2ms/step - loss: 7736.6670
Epoch 9/100
3/3 [==============================] - 0s 2ms/step - loss: 7642.1772
Epoch 10/100
3/3 [==============================] - 0s 2ms/step - loss: 7539.0757
Epoch 11/100
3/3 [==============================] - 0s 2ms/step - loss: 7429.3579
Epoch 12/100
3/3 [==============================] - 0s 2ms/step - loss: 7315.1792
Epoch 13/100
3/3 [=======

In [ ]:
kfold_score

array([-1.6606411 , -1.58527088, -1.86035079])

In [ ]:
import numpy as np
np.mean(kfold_score)

-1.7020875897405876